name: 'GitHub Action Submodule Update (Directcommit)'
description: 'Update submodules and creates a new commit for parent repository'
author: 'releasehub, PaulRitter'

branding:
  icon: 'git-commit'
  color: 'yellow'

inputs:
  github_token:
    description: 'Github Token'
    required: true
  parent_branch:
    description: 'Branch to commit to'
    required: false
    default: 'main'
  parent_repository:
    description: 'Parent Repository'
    required: true
  
runs:
  using: 'composite'
  steps:
  - name: Checkout parent repository and branch
    uses: actions/checkout@v3
    with:
      token: ${{ inputs.github_token }}
      repository: ${{ inputs.parent_repository }}
      ref: ${{ inputs.parent_branch }}
      submodules: true
      fetch-depth: 0

  - name: Check for submodule updates
    id: check_submodule
    run: |
      git submodule update --remote --rebase
      git diff-index --quiet HEAD || echo "::set-output name=changed::true"
      git diff --quiet HEAD@{1} HEAD || echo "::set-output name=commit_needed::true"
      git diff --name-only HEAD@{1} HEAD > submodule_changes.txt || true

  - name: Create new commit and push changes
    if: steps.check_submodule.outputs.commit_needed == 'true'
    shell: bash
    run: |
      git config user.name "${GITHUB_ACTOR}"
      git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
      while IFS= read -r line; do
          submodule=$(basename "$line")
          git commit -am "Updated submodule: $submodule"
      done < submodule_changes.txt
      git push
