name: 'GitHub Action Submodule Update (Directcommit)'
description: 'Update submodules and creates a new commit for parent repository'
author: 'releasehub, PaulRitter'

branding:
  icon: 'git-commit'
  color: 'yellow'

inputs:
  github_token:
    description: 'Github Token'
    required: true
  parent_branch:
    description: 'Branch to commit to'
    required: false
    default: 'main'
  parent_repository:
    description: 'Parent Repository'
    required: true
  
runs:
  using: 'composite'
  steps:
    - name: Checkout parent repository and branch
      uses: actions/checkout@v3
      with:
        token: ${{ inputs.github_token }}
        repository: ${{ inputs.parent_repository }}
        ref: ${{ inputs.parent_branch }}
        submodules: true
        fetch-depth: 0

    - name: Set Git user name and email
      run: |
        git config user.name "$(git --no-pager show -s --format='%an')"
        git config user.email "$(git --no-pager show -s --format='%ae')"

    - name: Create new commit and push changes
      run: |
        git submodule update --remote
        git commit -am "updating submodules"
        git push
